CREATE DATABASE card_game;

CREATE TABLE IF NOT EXISTS users (
    id INT NOT NULL AUTO_INCREMENT KEY,
    login VARCHAR(15) NOT NULL UNIQUE,
    password VARCHAR(100) NOT NULL,
    name TEXT NOT NULL,
    email VARCHAR(50) NOT NULL UNIQUE,
    win INT NOT NULL DEFAULT 0,
    lose INT NOT NULL DEFAULT 0
);